AZIIZAH OKI SHOFRINA <br>
2109106004 <br>
INFORMATIKA A'21

#### Import modul

In [1]:
import tensorflow as tf

# No. 1
### Buatlah sebuah tensor dengan shape (5, 5) dengan nilai random yang disimpan dalam variable random_tensor.

In [2]:
random_tensor = tf.random.normal([5, 5], dtype=tf.float64)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.28487729, -0.80799284,  0.28740661, -0.59635212, -0.35390189],
       [-0.16313212,  1.66439882,  1.34767726, -0.19060832, -0.20503531],
       [-0.84975082,  0.81756306, -0.54036268, -0.80801716, -1.11108208],
       [ 0.64418041,  1.01724695, -0.63694441, -0.23742979, -0.60647045],
       [ 2.48886485, -0.08606235, -0.78910074, -0.6377799 ,  1.11889344]])>

# No. 2
### Buatlah sebuah tensor dengan shape (5, 5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [3]:
prime_tensor = tf.convert_to_tensor(
    [[2,  3,  5,  7,  11],
     [13, 17, 19, 23, 29],
     [31, 37, 41, 43, 47],
     [53, 59, 61, 67, 71],
     [73, 79, 83, 89, 97]],
     dtype=tf.float64
)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]])>

# No. 3
### Tampilkan dimensi dari kedua variable tersebut.

### Dimension Display random_tensor
#### Menggunakan .shape

In [4]:
random_tensor.shape

TensorShape([5, 5])

#### Menggunakan .get_shape

In [5]:
random_tensor.get_shape

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.28487729, -0.80799284,  0.28740661, -0.59635212, -0.35390189],
       [-0.16313212,  1.66439882,  1.34767726, -0.19060832, -0.20503531],
       [-0.84975082,  0.81756306, -0.54036268, -0.80801716, -1.11108208],
       [ 0.64418041,  1.01724695, -0.63694441, -0.23742979, -0.60647045],
       [ 2.48886485, -0.08606235, -0.78910074, -0.6377799 ,  1.11889344]])>>

#### Menggunakan tf.shape()

In [6]:
tf.shape(random_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### Dimension Display prime_tensor

#### Menggunakan .shape

In [7]:
prime_tensor.shape

TensorShape([5, 5])

#### Menggunakan .get_shape

In [8]:
prime_tensor.get_shape

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]])>>

#### Menggunakan tf.shape()

In [9]:
tf.shape(prime_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

# No. 4
### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

#### Penjumlahan (tf.add())

In [10]:
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 3.28487729,  2.19200716,  5.28740661,  6.40364788, 10.64609811],
       [12.83686788, 18.66439882, 20.34767726, 22.80939168, 28.79496469],
       [30.15024918, 37.81756306, 40.45963732, 42.19198284, 45.88891792],
       [53.64418041, 60.01724695, 60.36305559, 66.76257021, 70.39352955],
       [75.48886485, 78.91393765, 82.21089926, 88.3622201 , 98.11889344]])>

#### Pengurangan (tf.subtract())

In [11]:
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ -0.71512271,  -3.80799284,  -4.71259339,  -7.59635212,
        -11.35390189],
       [-13.16313212, -15.33560118, -17.65232274, -23.19060832,
        -29.20503531],
       [-31.84975082, -36.18243694, -41.54036268, -43.80801716,
        -48.11108208],
       [-52.35581959, -57.98275305, -61.63694441, -67.23742979,
        -71.60647045],
       [-70.51113515, -79.08606235, -83.78910074, -89.6377799 ,
        -95.88110656]])>

#### Perkalian (tf.multiply())

In [12]:
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[  2.56975458,  -2.42397852,   1.43703305,  -4.17446482,
         -3.89292078],
       [ -2.12071761,  28.29477988,  25.60586786,  -4.38399141,
         -5.94602396],
       [-26.34227554,  30.24983311, -22.15486995, -34.74473771,
        -52.22085755],
       [ 34.14156174,  60.01756986, -38.85360909, -15.90779623,
        -43.05940184],
       [181.68713425,  -6.79892584, -65.49536166, -56.76241126,
        108.53266329]])>

#### Pembagian (tf.divide())

In [13]:
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 0.64243865, -0.26933095,  0.05748132, -0.08519316, -0.0321729 ],
       [-0.01254862,  0.09790581,  0.07093038, -0.00828732, -0.00707018],
       [-0.02741132,  0.0220963 , -0.01317958, -0.0187911 , -0.02364004],
       [ 0.01215435,  0.01724147, -0.01044171, -0.00354373, -0.00854184],
       [ 0.03409404, -0.0010894 , -0.00950724, -0.00716607,  0.01153498]])>

#### Pangkat (tf.pow())

In [14]:
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.65090966e+00, -5.27500091e-01,  1.96102786e-03,
        -2.68237417e-02, -1.09071601e-05],
       [-5.79446525e-11,  5.77265722e+03,  2.89822489e+02,
        -2.77499848e-17, -1.10415754e-20],
       [-6.42746059e-03,  5.79811170e-04, -1.09672888e-11,
        -1.04492476e-04, -1.41276084e+02],
       [ 7.54046664e-11,  2.74256736e+00, -1.12251825e-12,
        -1.44830325e-42, -3.79738568e-16],
       [ 8.09274721e+28, -7.08343301e-85, -2.89730046e-09,
        -4.12765898e-18,  5.40140110e+04]])>

#### Logaritma (tf.math.log())

In [15]:
tf.math.log(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 0.25066322,         nan, -1.24685731,         nan,         nan],
       [        nan,  0.50946399,  0.29838256,         nan,         nan],
       [        nan, -0.20142725,         nan,         nan,         nan],
       [-0.43977645,  0.01709991,         nan,         nan,         nan],
       [ 0.91182672,         nan,         nan,         nan,  0.11234019]])>

# No. 5
### Tampilkan nilai maksimum dan minimum dari variable random_tensor.

#### Nilai maksimum dari kolom

In [16]:
tf.argmax(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 1, 1, 1, 4], dtype=int64)>

#### Nilai maksimum dari baris

In [17]:
tf.argmax(random_tensor, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 1, 1, 0], dtype=int64)>

#### Nilai minimum dari kolom

In [18]:
tf.argmin(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 0, 4, 2, 2], dtype=int64)>

#### Nilai minimum dari baris

In [19]:
tf.argmin(random_tensor, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 4, 4, 2, 2], dtype=int64)>

# No. 6
### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

#### Hasil penggabungan berdasarkan dimensi kolom

In [20]:
hasil_concat = tf.concat(
    [random_tensor, prime_tensor],
    axis=0
)
hasil_concat

<tf.Tensor: shape=(10, 5), dtype=float64, numpy=
array([[ 1.28487729e+00, -8.07992841e-01,  2.87406610e-01,
        -5.96352117e-01, -3.53901889e-01],
       [-1.63132123e-01,  1.66439882e+00,  1.34767726e+00,
        -1.90608322e-01, -2.05035309e-01],
       [-8.49750824e-01,  8.17563057e-01, -5.40362682e-01,
        -8.08017156e-01, -1.11108208e+00],
       [ 6.44180410e-01,  1.01724695e+00, -6.36944411e-01,
        -2.37429794e-01, -6.06470448e-01],
       [ 2.48886485e+00, -8.60623524e-02, -7.89100743e-01,
        -6.37779902e-01,  1.11889344e+00],
       [ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  1.10000000e+01],
       [ 1.30000000e+01,  1.70000000e+01,  1.90000000e+01,
         2.30000000e+01,  2.90000000e+01],
       [ 3.10000000e+01,  3.70000000e+01,  4.10000000e+01,
         4.30000000e+01,  4.70000000e+01],
       [ 5.30000000e+01,  5.90000000e+01,  6.10000000e+01,
         6.70000000e+01,  7.10000000e+01],
       [ 7.30000000e+01,  7.90000

#### Dimensi hasil penggabungan di kolom

In [21]:
hasil_concat.shape

TensorShape([10, 5])

#### Hasil penggabungan berdasarkan dimensi baris

In [22]:
hasil_concat = tf.concat(
    [random_tensor, prime_tensor],
    axis=1
)
hasil_concat

<tf.Tensor: shape=(5, 10), dtype=float64, numpy=
array([[ 1.28487729e+00, -8.07992841e-01,  2.87406610e-01,
        -5.96352117e-01, -3.53901889e-01,  2.00000000e+00,
         3.00000000e+00,  5.00000000e+00,  7.00000000e+00,
         1.10000000e+01],
       [-1.63132123e-01,  1.66439882e+00,  1.34767726e+00,
        -1.90608322e-01, -2.05035309e-01,  1.30000000e+01,
         1.70000000e+01,  1.90000000e+01,  2.30000000e+01,
         2.90000000e+01],
       [-8.49750824e-01,  8.17563057e-01, -5.40362682e-01,
        -8.08017156e-01, -1.11108208e+00,  3.10000000e+01,
         3.70000000e+01,  4.10000000e+01,  4.30000000e+01,
         4.70000000e+01],
       [ 6.44180410e-01,  1.01724695e+00, -6.36944411e-01,
        -2.37429794e-01, -6.06470448e-01,  5.30000000e+01,
         5.90000000e+01,  6.10000000e+01,  6.70000000e+01,
         7.10000000e+01],
       [ 2.48886485e+00, -8.60623524e-02, -7.89100743e-01,
        -6.37779902e-01,  1.11889344e+00,  7.30000000e+01,
         7.90000000e+

#### Dimensi hasil penggabungan di baris

In [23]:
hasil_concat.shape


TensorShape([5, 10])

# No. 7
### Tampilkan hasil sorting dari kedua variable di atas (descending).

#### Sorting random_tensor

In [24]:
tf.sort(random_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.28487729,  0.28740661, -0.35390189, -0.59635212, -0.80799284],
       [ 1.66439882,  1.34767726, -0.16313212, -0.19060832, -0.20503531],
       [ 0.81756306, -0.54036268, -0.80801716, -0.84975082, -1.11108208],
       [ 1.01724695,  0.64418041, -0.23742979, -0.60647045, -0.63694441],
       [ 2.48886485,  1.11889344, -0.08606235, -0.6377799 , -0.78910074]])>

#### Sorting prime_tensor

In [25]:
tf.sort(prime_tensor, direction="DESCENDING")

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]])>