AZIIZAH OKI SHOFRINA <br>
2109106004 <br>
INFORMATIKA A'21

#### Import modul

In [1]:
import tensorflow as tf

# No. 1
### Buatlah sebuah tensor dengan shape (5, 5) dengan nilai random yang disimpan dalam variable random_tensor.

In [1]:
random_tensor = tf.random.normal([5, 5], dtype=tf.float64)
print(random_tensor)

NameError: name 'tf' is not defined

# No. 2
### Buatlah sebuah tensor dengan shape (5, 5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [3]:
prime_tensor = tf.convert_to_tensor(
    [[2,  3,  5,  7,  11],
     [13, 17, 19, 23, 29],
     [31, 37, 41, 43, 47],
     [53, 59, 61, 67, 71],
     [73, 79, 83, 89, 97]],
     dtype=tf.float64
)
print(prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]])>

# No. 3
### Tampilkan dimensi dari kedua variable tersebut.

### Dimension Display random_tensor
#### Menggunakan .shape

In [4]:
print(random_tensor.shape)

TensorShape([5, 5])

#### Menggunakan .get_shape

In [5]:
print(random_tensor.get_shape)

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 0.34541606, -0.94437116, -0.13089938,  1.01322063,  0.62381698],
       [ 0.8440215 ,  0.31081136, -2.30397024,  0.58915141,  0.04920914],
       [ 0.33102955, -0.28884039,  1.49577005,  0.80662549,  0.89507286],
       [ 2.42467656, -0.38594212, -0.19289149,  1.61783722,  0.60896664],
       [-1.14273552, -0.21064338, -0.62970197,  0.7027827 ,  0.04564779]])>>

#### Menggunakan tf.shape()

In [6]:
print(tf.shape(random_tensor))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### Dimension Display prime_tensor

#### Menggunakan .shape

In [7]:
print(prime_tensor.shape)

TensorShape([5, 5])

#### Menggunakan .get_shape

In [8]:
print(prime_tensor.get_shape)

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]])>>

#### Menggunakan tf.shape()

In [9]:
print(tf.shape(prime_tensor))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

# No. 4
### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

#### Penjumlahan (tf.add())

In [10]:
print(tf.add(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 2.34541606,  2.05562884,  4.86910062,  8.01322063, 11.62381698],
       [13.8440215 , 17.31081136, 16.69602976, 23.58915141, 29.04920914],
       [31.33102955, 36.71115961, 42.49577005, 43.80662549, 47.89507286],
       [55.42467656, 58.61405788, 60.80710851, 68.61783722, 71.60896664],
       [71.85726448, 78.78935662, 82.37029803, 89.7027827 , 97.04564779]])>

#### Pengurangan (tf.subtract())

In [11]:
print(tf.subtract(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ -1.65458394,  -3.94437116,  -5.13089938,  -5.98677937,
        -10.37618302],
       [-12.1559785 , -16.68918864, -21.30397024, -22.41084859,
        -28.95079086],
       [-30.66897045, -37.28884039, -39.50422995, -42.19337451,
        -46.10492714],
       [-50.57532344, -59.38594212, -61.19289149, -65.38216278,
        -70.39103336],
       [-74.14273552, -79.21064338, -83.62970197, -88.2972173 ,
        -96.95435221]])>

#### Perkalian (tf.multiply())

In [12]:
print(tf.multiply(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[  0.69083212,  -2.83311349,  -0.65449691,   7.09254438,
          6.86198683],
       [ 10.97227947,   5.2837931 , -43.77543462,  13.55048251,
          1.427065  ],
       [ 10.26191617, -10.68709441,  61.32657201,  34.684896  ,
         42.06842462],
       [128.50785771, -22.77058526, -11.7663806 , 108.39509371,
         43.23663167],
       [-83.41969294, -16.64082729, -52.26526339,  62.54765995,
          4.42783568]])>

#### Pembagian (tf.divide())

In [13]:
print(tf.divide(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 0.17270803, -0.31479039, -0.02617988,  0.1447458 ,  0.05671063],
       [ 0.06492473,  0.01828302, -0.12126159,  0.02561528,  0.00169687],
       [ 0.01067837, -0.0078065 ,  0.0364822 ,  0.01875873,  0.0190441 ],
       [ 0.04574861, -0.00654139, -0.00316216,  0.02414682,  0.00857699],
       [-0.01565391, -0.00266637, -0.00758677,  0.00789643,  0.0004706 ]])>

#### Pangkat (tf.pow())

In [14]:
print(tf.pow(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.19312255e-001, -8.42225046e-001, -3.84315566e-005,
         1.09629682e+000,  5.56710158e-003],
       [ 1.10305105e-001,  2.35747446e-009, -7.71010775e+006,
         5.19062021e-006,  1.17307817e-038],
       [ 1.30577944e-015, -1.10749842e-020,  1.47726410e+007,
         9.70271926e-005,  5.46190793e-003],
       [ 2.43585902e+020, -4.02539692e-025, -2.53569194e-044,
         9.96857559e+013,  5.08321887e-016],
       [-1.69839248e+004, -3.63310480e-054, -2.12916456e-017,
         2.32848968e-014,  9.19849603e-131]])>

#### Logaritma (tf.math.log())

In [15]:
print(tf.math.log(random_tensor, prime_tensor))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[-1.06300562,         nan,         nan,  0.013134  , -0.47189825],
       [-0.16957731, -1.16856911,         nan, -0.52907206, -3.01167594],
       [-1.10554762,         nan,  0.40264116, -0.2148958 , -0.11085015],
       [ 0.88569814,         nan,         nan,  0.48109021, -0.49599179],
       [        nan,         nan,         nan, -0.35270754, -3.08680007]])>

# No. 5
### Tampilkan nilai maksimum dan minimum dari variable random_tensor.

#### Nilai maksimum dari kolom

In [16]:
print(tf.argmax(random_tensor, axis=0))

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 1, 2, 3, 2], dtype=int64)>

#### Nilai maksimum dari baris

In [17]:
print(tf.argmax(random_tensor, axis=1))

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 0, 2, 0, 3], dtype=int64)>

#### Nilai minimum dari kolom

In [18]:
print(tf.argmin(random_tensor, axis=0))

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 0, 1, 1, 4], dtype=int64)>

#### Nilai minimum dari baris

In [2]:
print(tf.argmin(random_tensor, axis=1))

NameError: name 'tf' is not defined

# No. 6
### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

#### Hasil penggabungan berdasarkan dimensi kolom

In [20]:
hasil_concat = tf.concat(
    [random_tensor, prime_tensor],
    axis=0
)
print(hasil_concat)

<tf.Tensor: shape=(10, 5), dtype=float64, numpy=
array([[ 3.45416060e-01, -9.44371164e-01, -1.30899382e-01,
         1.01322063e+00,  6.23816985e-01],
       [ 8.44021498e-01,  3.10811359e-01, -2.30397024e+00,
         5.89151414e-01,  4.92091379e-02],
       [ 3.31029554e-01, -2.88840390e-01,  1.49577005e+00,
         8.06625488e-01,  8.95072864e-01],
       [ 2.42467656e+00, -3.85942123e-01, -1.92891485e-01,
         1.61783722e+00,  6.08966643e-01],
       [-1.14273552e+00, -2.10643383e-01, -6.29701969e-01,
         7.02782696e-01,  4.56477905e-02],
       [ 2.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         7.00000000e+00,  1.10000000e+01],
       [ 1.30000000e+01,  1.70000000e+01,  1.90000000e+01,
         2.30000000e+01,  2.90000000e+01],
       [ 3.10000000e+01,  3.70000000e+01,  4.10000000e+01,
         4.30000000e+01,  4.70000000e+01],
       [ 5.30000000e+01,  5.90000000e+01,  6.10000000e+01,
         6.70000000e+01,  7.10000000e+01],
       [ 7.30000000e+01,  7.90000

#### Dimensi hasil penggabungan di kolom

In [21]:
print(hasil_concat.shape)

TensorShape([10, 5])

#### Hasil penggabungan berdasarkan dimensi baris

In [22]:
hasil_concat = tf.concat(
    [random_tensor, prime_tensor],
    axis=1
)
print(hasil_concat)

<tf.Tensor: shape=(5, 10), dtype=float64, numpy=
array([[ 3.45416060e-01, -9.44371164e-01, -1.30899382e-01,
         1.01322063e+00,  6.23816985e-01,  2.00000000e+00,
         3.00000000e+00,  5.00000000e+00,  7.00000000e+00,
         1.10000000e+01],
       [ 8.44021498e-01,  3.10811359e-01, -2.30397024e+00,
         5.89151414e-01,  4.92091379e-02,  1.30000000e+01,
         1.70000000e+01,  1.90000000e+01,  2.30000000e+01,
         2.90000000e+01],
       [ 3.31029554e-01, -2.88840390e-01,  1.49577005e+00,
         8.06625488e-01,  8.95072864e-01,  3.10000000e+01,
         3.70000000e+01,  4.10000000e+01,  4.30000000e+01,
         4.70000000e+01],
       [ 2.42467656e+00, -3.85942123e-01, -1.92891485e-01,
         1.61783722e+00,  6.08966643e-01,  5.30000000e+01,
         5.90000000e+01,  6.10000000e+01,  6.70000000e+01,
         7.10000000e+01],
       [-1.14273552e+00, -2.10643383e-01, -6.29701969e-01,
         7.02782696e-01,  4.56477905e-02,  7.30000000e+01,
         7.90000000e+

#### Dimensi hasil penggabungan di baris

In [23]:
print(hasil_concat.shape)


TensorShape([5, 10])

# No. 7
### Tampilkan hasil sorting dari kedua variable di atas (descending).

#### Sorting random_tensor

In [24]:
print(tf.sort(random_tensor, direction="DESCENDING"))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[ 1.01322063,  0.62381698,  0.34541606, -0.13089938, -0.94437116],
       [ 0.8440215 ,  0.58915141,  0.31081136,  0.04920914, -2.30397024],
       [ 1.49577005,  0.89507286,  0.80662549,  0.33102955, -0.28884039],
       [ 2.42467656,  1.61783722,  0.60896664, -0.19289149, -0.38594212],
       [ 0.7027827 ,  0.04564779, -0.21064338, -0.62970197, -1.14273552]])>

#### Sorting prime_tensor

In [25]:
print(tf.sort(prime_tensor, direction="DESCENDING"))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]])>